Goph Keeper
yury-nazarov/goph_keeper pull request #3
Opened 2023-01-08 17:22 UTC by yury-nazarov

Goph Keeper сервис хранения секретов
- API сервер
- CLI клиент

2023-01-09 20:49 UTC, bambruysk requested changes
Нужно избавиться от пакетов tools - разнести их на несколько

2023-01-09 20:49 UTC, bambruysk commented on internal/cli/tools/tools.go
> +	Token string
Без необходимостии не стоит делать поя публичными

2023-01-09 20:49 UTC, bambruysk commented on internal/cli/tools/tools.go
> +type cliTools struct {
Это божестивенный класс (god class) - делает слишком много) Это плохой стиль. Лучше рназбит на неасколько структур и пакетов

2023-01-09 20:49 UTC, bambruysk commented on internal/cli/secretDelete.go
> +		httpStatus, _, err  := ct.HTTPClient(apiServer, http.MethodDelete, nil)
не стоит создавать клиент при каждом запросе. 
адрес сервера известен, так зачем его какждый раз перевычислять?

2023-01-09 20:49 UTC, bambruysk commented on internal/cli/tools/tools.go
> +		c.Log.Warn(fmt.Sprintf("can't read file: %s", c.storage), zap.String("error", err.Error()))
странный метод формироввания сообщения в лог есть же Warnf - сразу с форматированием

2023-01-09 20:49 UTC, bambruysk commented on internal/server/handler/handler.go
> +	return
return не нужен если ничего не возвращает

2023-01-09 20:49 UTC, bambruysk commented on internal/server/handler/handler.go
> +	if errors.As(err, &err404) {
здесь потенциальная проблема - As записывает во второй аргумент ошибку. В многопоточном режиме могут быть гонки

2023-01-09 20:49 UTC, bambruysk commented on internal/server/handler/handler.go
> +		w.WriteHeader(http.StatusInternalServerError)
Хидер пишется два раза, не очень Лучше 172 переместить вниз ( сначала негативнве кейсы и вм конце позитивный

2023-01-09 20:49 UTC, bambruysk commented on internal/server/handler/handler.go
> +type Controller struct {
Для секретов и авторизации можно использловать отдельные контроллеры

2023-01-09 20:49 UTC, bambruysk commented on pkg/tools/Err500.go
> +	message string
Если нет доп полей в структуре, то создавать кастомный тип ошибки ни к чему

2023-01-09 20:49 UTC, bambruysk commented on pkg/tools/Err500.go
> +	message string
можно поле с кодом добавить в учебно-тренировочных целях

2023-01-09 20:49 UTC, bambruysk commented on internal/server/service/secret/secret.go
> +			zap.String("method", "secret.PutByID"),
метода имя не совпадает с функцией

2023-01-09 20:49 UTC, bambruysk commented on internal/server/service/auth/auth.go
> +	sessions inmemory.Sessions
лучше объявлять интерфейсы там где они используются, а не импортировать из других пакетов

2023-01-14 08:14 UTC, yury-nazarov commented on internal/cli/secretDelete.go
> +		httpStatus, _, err  := ct.HTTPClient(apiServer, http.MethodDelete, nil)
Клиент создается каждый раз, т.к. рантайм клиента это запуск отдельной команды.

2023-01-19 22:08 UTC, bambruysk approved these changes
Принято

2023-01-20 04:54 UTC, merged